---
# Copy this template to config.yml, then make changes
# as needed for your local install.

# Port to serve the website on.
port: 54321

# Paths are relative to the location of superman_server.py
# File specifying the locations and contents of dataset files.
datasets: datasets.yml

# Location of the server's logfile.
# On restart, the previous logfile will be saved to a new name
# based on the timestamp: <logfile>.<timestamp>
logfile: logs/server.log

# Login password for access to private datasets and tools.
# If not provided, the server will disable login
# and won't load any private datasets.
# NOTE: change this from the default password,
# or your "private" data will not be!
password: mypassword123

# Random string for encrypting cookie data.
# If not provided, the server will generate a new secret on startup.
# NOTE: Don't specify this unless you know what you're doing!
# cookie_secret: "<some random string>"

